buildPack: maven-java11
pipelines:
    release:
      promote:
        steps:
        - command: jx step create pr chart --name fmtok8s-api-gateway --version $VERSION  --repo https://github.com/salaboy/fmtk8s-kubecon-app.git

