spring:
  cloud:
    gateway:
      routes:
      - id: c4p
        uri: http://fmtok8s-c4p/
        predicates:
        - Path=/c4p/**
        filters:
          - RewritePath=/c4p/(?<id>.*), /$\{id}

