spring:
  cloud:
    gateway:
      routes:
      - id: c4p
        uri: http://fmtok8s-c4p/
        predicates:
        - Path=/new/c4p/**
        filters:
          - RewritePath=/new/c4p/(?<id>.*), /$\{id}
      - id: monolith
        uri: http://fmtok8s-monolith/
        predicates:
        - Path=/monolith/**
        filters:
          - RewritePath=/monolith/(?<id>.*), /$\{id}

