spring:
  web:
    resources:
      static-locations: "file:static/" #for dev file:./target/static/ for docker static/
  webflux:
    static-path-pattern: "/**" # https://github.com/spring-cloud/spring-cloud-gateway/issues/1339
  profiles:
    active:
  application:
    name:
      fmtok8s-api-gateway-service
  cloud:
    gateway:
      #filter: #https://cloud.spring.io/spring-cloud-gateway/reference/html/#the-secureheaders-gatewayfilter-factory
      filter:
        secure-headers:
          enabled: true
      default-filters:
        - SecureHeaders
        - TokenRelay=
        - RemoveRequestHeader=Cookie
      httpclient:
        wiretap: true
      httpserver:
          wiretap: true
      routes:
      - id: agenda
        uri: ${AGENDA_SERVICE:http://fmtok8s-agenda}
        predicates:
          - Path=/agenda/**
        filters:
          - RewritePath=/agenda/(?<id>.*), /$\{id}
          - name: CircuitBreaker
            args:
              name: agendaCircuitBreaker
              fallbackUri: forward:/api/agendaNotAvailable
      - id: c4p
        uri: ${C4P_SERVICE:http://fmtok8s-c4p}
        predicates:
        - Path=/c4p/**
        filters:
          - RewritePath=/c4p/(?<id>.*), /$\{id}
          - name: CircuitBreaker
            args:
              name: c4pCircuitBreaker
              fallbackUri: forward:/api/c4pNotAvailable
      - id: email
        uri: ${EMAIL_SERVICE:http://fmtok8s-email}
        predicates:
        - Path=/email/**
        filters:
          - RewritePath=/email/(?<id>.*), /$\{id}
          - name: CircuitBreaker
            args:
              name: c4pCircuitBreaker
              fallbackUri: forward:/api/emailNotAvailable
      - id: speakers
        uri: ${SPEAKERS_SERVICE:http://fmtok8s-speakers}
        predicates:
          - Path=/speakers/**
        filters:
          - RewritePath=/speakers/(?<id>.*), /$\{id}
      - id: sponsors
        uri: ${SPONSORS_SERVICE:http://fmtok8s-sponsors}
        predicates:
          - Path=/sponsors/**
        filters:
          - RewritePath=/sponsors/(?<id>.*), /$\{id}
      - id: tickets
        uri: ${TICKETS_SERVICE:http://tickets-service}
        predicates:
          - Path=/tickets/**
        filters:
          - RewritePath=/tickets/(?<id>.*), /$\{id}
      - id: payments
        uri: ${PAYMENTS_SERVICE:http://payments-service.default.svc.cluster.local}
        predicates:
          - Path=/payments/**
        filters:
          - RewritePath=/payments/(?<id>.*), /$\{id}
          - AddResponseHeader=X-Frame-Options, SAMEORIGIN
      - id: queue
        uri: ${QUEUE_SERVICE:http://queue-service.default.svc.cluster.local}
        predicates:
          - Path=/queue/**
        filters:
          - RewritePath=/queue/(?<id>.*), /$\{id}
      - id: broker
        uri: ${K_SINK:http://broker-ingress.knative-eventing.svc.cluster.local}
        predicates:
          - Path=/broker
        filters:
          - RewritePath=${K_SINK_POST_FIX:"/broker, default/default"}

#  security:
#    oauth2:
#      client:
#        registration:
#          oidc:
#            scope:
#              - openid

management:

  endpoints:
    web:
      exposure:
        include: health, gateway, info, prometheus, metrics, threaddump
  endpoint:
    loggers:
      enabled: true
    info:
      enabled: true
      show-details: always
    gateway:
      enabled: true
      show-details: always
    health:
      probes:
        enabled: true
      enabled: true
      show-details: always
      group:
        liveness:
          include: livenessState
          show-details: always
        readiness:
          include: readinessState
          show-details: always

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: INFO
    com:
      salaboy:
        conferences:
          site: INFO