# Default values for node projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: ghcr.io/salaboy/fmtok8s-frontend
  tag: main
  pullPolicy: Always


# define environment variables here as a map of key: value
env:
  "FEATURE_C4P_ENABLED"g: "true"
# enable this flag to use knative serve to deploy the app
knativeDeploy: false

service:
  name: fmtok8s-frontend
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
  annotations:
resources:
  limits:
    cpu: "1"
    memory: 256Mi
  requests:
    cpu: "0.1"
    memory: 256Mi
probePath: /actuator/health
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  failureThreshold: 1
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
