apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}"-cdf
  labels:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"-cdf
    spec:
      restartPolicy: Never
      containers:
        - name: cdf-upgrade-service
          image: gcr.io/camunda-researchanddevelopment/cd-flow:0.0.10
          script: |
             #!/usr/bin/env sh
            export CDF_SINK=http://backend.35.204.61.61.xip.io/api/events
            cdf service updated --env staging --service fmtok8s-api-gateway --version {{ .Release.Version }} || true
