apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-install"
  labels:
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-install-job"
    spec:
      restartPolicy: Never
      containers:
        - name: cdf-upgrade-service
          image: gcr.io/camunda-researchanddevelopment/cd-flow:0.0.12
          command: ["/bin/sh","-c"]
          args: ["export", "CDF_SINK=http://backend.35.204.61.61.xip.io/api/events",
                    "&&",
                    "cdf", "service", "created", "--env", "staging", "--name", "fmtok8s-api-gateway", "--version", "{{ .Release.Version }}",
                    "||", "true" ]

#            export CDF_SINK=http://backend.35.204.61.61.xip.io/api/events
#            cdf service created --env staging --name fmtok8s-api-gateway --version {{ .Release.Version }} || true

---

apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-upgrade"
  labels:
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-upgrade-job"
    spec:
      restartPolicy: Never
      containers:
        - name: cdf-upgrade-service
          image: gcr.io/camunda-researchanddevelopment/cd-flow:0.0.12
          command: ["/bin/sh","-c"]
          args: ["export", "CDF_SINK=http://backend.35.204.61.61.xip.io/api/events",
                  "&&",
                  "cdf", "service", "updated", "--env", "staging", "--name", "fmtok8s-api-gateway", "--version", "{{ .Release.Version }}",
                  "||", "true" ]