name: Github Actions
on: [push]

permissions:
  packages: write

jobs:
  Build-Application:
    runs-on: ubuntu-20.04
    steps:
      # Info
      - name: Info
        run: echo "Building ${{ github.repository }} application, branch/tag ${{ github.ref_name }}"

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt

      - name: Build with maven
        run: mvn package

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/salaboy/fmtok8s-api-gateway
          tags: |
            type=ref,event=branch
            type=ref,event=pr
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: salaboy
          password: ${{ secrets.PACKAGE_TOKEN }}

      - name: Build and push docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
      - name: Update Chart.yaml
        uses: fjogeleit/yaml-update-action@main
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          valueFile: 'helm/fmtok8s-api-gateway/Chart.yaml'
          propertyPath: 'version'
          value: '${{ github.ref_name }}'
          commitChange: false
          updateFile: true

      - name: Helm Chart Release
        uses: stefanprodan/helm-gh-pages@master
        with:
          charts_dir: helm
          token: ${{ secrets.PACKAGE_TOKEN }}
          repository: helm
          branch: gh-pages
          owner: salaboy
