name: Github Actions
on: [push]
jobs:
  Build-Application:
    runs-on: ubuntu-20.04
    steps:
      - name: Logging
        run: echo "Building ${{ github.repository }} application, branch/tag ${{ github.ref_name }}."
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt
      - name: Build with maven
        run: mvn package
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: salaboy
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Docker Image
        run: |
          docker build . --tag ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          docker push ghcr.io/${{ github.repository }}:${{ github.ref_name }}
      - name: Update Chart.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: '../helm/fmtok8s-api-gateway/Chart.yaml'
          propertyPath: 'version'
          value: ${{ github.ref_name }}
          commitChange: false
          updateFile: true
      - name: Helm Chart Release
        uses: stefanprodan/helm-gh-pages@master
        with:
          charts_dir: helm
          token: ${{ secrets.PACKAGE_TOKEN }}
          repository: helm
          branch: gh-pages
          owner: salaboy
