name: GitHub Actions Demo
on: [push]
jobs:
  Build-Application:
    runs-on: ubuntu-20.04
    steps:
      - name: Logging
        run: echo "Building ${{ github.repository }} application, branch ${{ github.ref }}."
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt
      - name: Build with maven
        run: mvn package
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Docker Image
        run: |
          docker build . --tag ghcr.io/${{ github.actor }}/fmtok8s-api-gateway:0.1.0
          docker push ghcr.io/${{ github.actor }}/fmtok8s-api-gateway:0.1.0
